### ISSUE TITLE
TypeError: Cannot read property 'appname' of undefined

### ISSUE THREAD

**Issue by evan9523** [Qolzam/firestore-social-backend#11]
after "firebase deploy" this error shows up :

Error: Error occurred while parsing your function triggers.

TypeError: Cannot read property 'appname' of undefined
    at Object.<anonymous> (C:\Users\SUBHAM\firestore-social-backend\functions\dist\index.js:1:5536)
    at r (C:\Users\SUBHAM\firestore-social-backend\functions\dist\index.js:1:155)
    at Object.<anonymous> (C:\Users\SUBHAM\firestore-social-backend\functions\dist\index.js:1:4766)
    at r (C:\Users\SUBHAM\firestore-social-backend\functions\dist\index.js:1:155)
    at C:\Users\SUBHAM\firestore-social-backend\functions\dist\index.js:1:954
    at Object.<anonymous> (C:\Users\SUBHAM\firestore-social-backend\functions\dist\index.js:1:964)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

**Comment by Qolzam** [comment]
duplicate (#1 )
