### ISSUE TITLE
npm install fails with a exit code 1

### ISSUE THREAD

**Issue by akarumuru** [Qolzam/firestore-social-backend#6]
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\TestProject\\firestore-social-backend\\functions\\node_modules\\grpc\\src\\node\\extension_binary\\node-v67-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\TestProject\\firestore-social-backend\\functions\\node_modules\\grpc\\src\\node\\extension_binary\\node-v67-win32-x64-unknown" "--napi_version=3" "--node_abi_napi=napi" "--python=c:\\Python\\27\\python.exe"
gyp ERR! cwd C:\TestProject\firestore-social-backend\functions\node_modules\grpc
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\TestProject\firestore-social-backend\functions\node_modules\grpc\src\node\extension_binary\node-v67-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\TestProject\firestore-social-backend\functions\node_modules\grpc\src\node\extension_binary\node-v67-win32-x64-unknown --napi_version=3 --node_abi_napi=napi --python=c:\Python\27\python.exe' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\TestProject\firestore-social-backend\functions\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\TestProject\\firestore-social-backend\\functions\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\TestProject\firestore-social-backend\functions\node_modules\grpc
node-pre-gyp ERR! node -v v11.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\TestProject\firestore-social-backend\functions\node_modules\grpc\src\node\extension_binary\node-v67-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\TestProject\firestore-social-backend\functions\node_modules\grpc\src\node\extension_binary\node-v67-win32-x64-unknown --napi_version=3 --node_abi_napi=napi --python=c:\Python\27\python.exe' (1)
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN firebase-functions@1.1.0 requires a peer of firebase-admin@~5.12.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.15.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.15.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\akarumuru\AppData\Roaming\npm-cache\_logs\2018-10-31T18_23_27_928Z-debug.log

What am i missing?
I Searched different blog posts, seems to be a common issue but none of the solutions worked for me.
Need some help

**Comment by akarumuru** [comment]
Any help here?

**Comment by Qolzam** [comment]
Hello @akarumuru, not relate to React Social but please send me your os version if I can help you. if you're using Windows you should install all node-gyp dependencies with following commands:
```shell
$ npm install --global --production windows-build-tools 
```
and then install the package

```shell
$ npm install --global node-gyp
```

**Comment by akarumuru** [comment]
Firstly, thanks for the response @Qolzam, I already did that but still get the same exception.

**Comment by Qolzam** [comment]
@akarumuru can you send me information about the environment you are working?

**Comment by akarumuru** [comment]
@Qolzam I'm using a PC with windows 10
